### ISSUE TITLE
Creating cards with description = ''

### ISSUE THREAD

**Issue by isfuku** [vvaezian/metabase_api_python#10]
Copying a card or creating a card using custom_json with description = '' results in an non-informative error. My sugestion is to either add an informative error mensage, or to create a conditional statement such as "if custom_json['description'] = '' then custom_json['description']= None".

**Comment by vvaezian** [comment]
Hi @isfuku,
In Metabase API docs for creating a card ([link](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#post-apicard)) it says:
"`description` value may be nil, or if non-nil, value must be a non-blank string."
This seems to be the issue. I'll apply your suggestion, but note that `description` is not a required argument, you can just leave it out when using the `create_card` function with `custom_json`.
 
[This part](https://github.com/vvaezian/metabase_api_python/blob/9f304bf6ec19189e04e74b5baf4f8830c4cfe4b1/metabase_api/metabase_api.py#L231) of the `create_card` function docs may be helpful as well.
BTW, when creating a card, you can set `verbose=True` to print extra information.

**Comment by isfuku** [comment]
@vvaezian thanks dor the reply. I encountered the issue when copying a card with no description, that instead of generating a `custom_json` with null `description`, generated one with a blank string for `description`.

**Comment by vvaezian** [comment]
That is really weird, because the `copy_card` function doesn't change the `description`.

Please go the the card that produced the error when copying, get its ID (in the address bar, at the end: https://.../question/[card_id]), then run the following command, and let me know what you see as the value for the `description` key

`mb.get('/api/card/[card_id]')`

Please also provide the error message which you get when copying the card.

**Comment by isfuku** [comment]
It returns `'description': ''`, with error menssage `Card Creation Failed.` and `res = False`

**Comment by vvaezian** [comment]
I see. So the `description` in the original card was not `None`, but the empty string. This is still weird as how it was possible that empty string got set as the description of that card.
Anyways, I'll apply your suggestion in the code which would fix this rare situation.

**Comment by vvaezian** [comment]
Fixed in v0.2.8.

**Comment by vvaezian** [comment]
Hi @isfuku,
At Intellimenta we have developed [DataBot](https://intellimenta.com/products/databot/), a conversational analytics app that connects with **Metabase** and enables users to ask questions about data and visualize the results using natural language in their preferred language. 
If your company uses Metabase, DataBot can significantly enhance how your team and customers interact with data. If you're interested in learning more, you can book a demo using [this](https://outlook.office365.com/owa/calendar/booking@intellimenta.com/bookings/s/ZEMZuuM07U6C4Tr-GKUyOQ2) link. Happy to discuss further.
