### ISSUE TITLE
deepcopy collections give error:  if item['model'] == 'collection': TypeError: string indices must be integers

### ISSUE THREAD

**Issue by janwadebock** [vvaezian/metabase_api_python#22]
Traceback (most recent call last):
  File "metabase.py", line 42, in <module>
    mb.copy_collection(source_collection_id=17, destination_parent_collection_id=8, destination_collection_name='Vlaanderen_copy', deepcopy_dashboards=True, verbose=True)
  File "C:\Users\janwa\AppData\Local\Programs\Python\Python37\lib\site-packages\metabase_api\metabase_api.py", line 761, in copy_collection
    if item['model'] == 'collection':
TypeError: string indices must be integers

**Comment by vvaezian** [comment]
@janwadebock Thanks for the feedback.  
Which version of Metabase are you using? This may be related to recent changes Metabase made in their API

**Comment by janwadebock** [comment]
Hi Vahid,

I am using 0.40 version.  There is a new one 0.41 but that i don't t use
yet.

Thanks for you prompt reply.

Jan

**Comment by vvaezian** [comment]
@janwadebock It should work fine now.
Please upgrade to the new version (`pip install --upgrade metabase_api`) and test it out. 
Also check the [release notes](https://github.com/vvaezian/metabase_api_python/releases/tag/v0.2.13) regarding the changes to `copy_collection` function.

**Comment by janwadebock** [comment]
@vahid
Tx a lot ! Indeed the copy is working now, error is gone. Tx a lot for
fixing this so quickly. Super !!
