### ISSUE TITLE
Copy collection to root collection does not work

### ISSUE THREAD

**Issue by Sergei-Volkov** [vvaezian/metabase_api_python#23]
For my product I needed to copy my collection from root to root. I couldn't do it, unless I added the ternary operator to line 1005 of _metabase_api.py_ file. I used value of parameter = "Root", as the function _create_collection_ suggests
![Screenshot from 2021-10-18 17-54-23](https://user-images.githubusercontent.com/53339173/137756132-6bbb0c5d-1ab0-4e13-9299-029adff140c4.png)

**Comment by vvaezian** [comment]
Fixed in v0.2.14

**Comment by vvaezian** [comment]
Hi @Sergei-Volkov,
At Intellimenta we have developed [DataBot](https://intellimenta.com/products/databot/), a conversational analytics app that connects with Metabase and enables users to ask questions about data and visualize the results using natural language in their preferred language.
If your company uses Metabase, DataBot can significantly enhance how your team and customers interact with data. If you're interested in learning more, you can book a demo using [this](https://outlook.office365.com/owa/calendar/booking@intellimenta.com/bookings/s/ZEMZuuM07U6C4Tr-GKUyOQ2) link. Happy to discuss further.
