### ISSUE TITLE
KeyError: 'Native' for Clone_Card

### ISSUE THREAD

**Issue by BprillBA** [vvaezian/metabase_api_python#27]
When running clone_card the following error is generated: 

filters_data = card_info['dataset_query']['native']['template-tags']
KeyError: 'native'

Metabase Version: 0.41.2

**Comment by vvaezian** [comment]
Are you using this function for a Native question? Or is it for a custom/simple question?

**Comment by BprillBA** [comment]
This is being run on a simple question.

**Comment by vvaezian** [comment]
I'll add the functionality for non-native questions soon.

**Comment by vvaezian** [comment]
Fixed in v0.2.14

**Comment by vvaezian** [comment]
Hi @BprillBA,
At Intellimenta we have developed [DataBot](https://intellimenta.com/products/databot/), a conversational analytics app that connects with **Metabase** and enables users to ask questions about data and visualize the results using natural language in their preferred language.
If your company uses Metabase, DataBot can significantly enhance how your team and customers interact with data. If you're interested in learning more, you can book a demo using [this](https://outlook.office365.com/owa/calendar/booking@intellimenta.com/bookings/s/ZEMZuuM07U6C4Tr-GKUyOQ2) link. Happy to discuss further.
