### ISSUE TITLE
Update get_item_id and get_item_name

### ISSUE THREAD

**Issue by Dynnammo** [vvaezian/metabase_api_python#28]
As a developer, I want to get items from a Metabase instance only knowing their names.

Currently, `get_item_id` and `get_item_name` aren't fully working with objects like `database` or `collection`.

## Purpose
Complete those auxiliary with some new objects available : `dashboard`, `collection` and`pulse`

## Founding
Funded by [OpenSourcePolitics](https://opensourcepolitics.eu)

**Comment by vvaezian** [comment]
There are currently `get_db_id` and `get_collection_id` functions. I'll merge them with the `get_item_id` function on the weekend and try to cover all cases for `get_item_id` and `get_item_name` functions.

**Comment by vvaezian** [comment]
Implemented in v0.2.14
