### ISSUE TITLE
create_collection creates collections with names already in use

### ISSUE THREAD

**Issue by MoonBrain01** [vvaezian/metabase_api_python#48]
The create_collection method does not check if a collection with that name already exists.
I only noticed this when using the get_item_info method to get the details of the collection I had created and it returned the message "ValueError: There is more than one collection with the name"

**Comment by vvaezian** [comment]
In Metabase you can create multiple collections/cards/dashboards/etc with the same name. There is no issue with that as they have different IDs. So in the Python wrapper (the current package) the same functionality is replicated.

**Comment by vvaezian** [comment]
Hi @MoonBrain01,

At Intellimenta we have developed [DataBot](https://intellimenta.com/products/databot/), a conversational analytics app that connects with **Metabase** and enables users to ask questions about data and visualize the results using natural language in their preferred language.
If your company uses Metabase, DataBot can significantly enhance how your team and customers interact with data. If you're interested in learning more, you can book a demo using [this](https://outlook.office365.com/owa/calendar/booking@intellimenta.com/bookings/s/ZEMZuuM07U6C4Tr-GKUyOQ2) link. Happy to discuss further.
