### ISSUE TITLE
[Auth] Allow authentication via API token

### ISSUE THREAD

**Issue by simonezambonim** [vvaezian/metabase_api_python#49]
In Metabase v.49 it is possible to authenticate using an API Token. The [documentation](https://www.metabase.com/learn/administration/metabase-api#example-get-request) brings more detailed information.

Can it be added to the metabase-api project?

Thanks

**Comment by vvaezian** [comment]
Hi @simonezambonim. Yes, it will be added soon.

**Comment by vvaezian** [comment]
Added in v3.3
