### ISSUE TITLE
/put/dashboard/{id}/cards not working in v47

### ISSUE THREAD

**Issue by yasserN** [vvaezian/metabase_api_python#55]
A valid payload (taken directly from network monitoring) does not work. **I ran the same payload through the raw api and it works.** 
```
    cards_payload = {
            "cards": [
            {
                "id": 1285,
                "row": 0,
                "col": 0,
                "size_x": 24,
                "size_y": 3,
                "series": [],
                "visualization_settings": {
                "virtual_card": {
                    "display": "text",
                    "visualization_settings": {},
                    "dataset_query": {},
                    "archived": False
                },
                "text": "text updated via api"
                },
                "parameter_mappings": []
            }
            ],
            "ordered_tabs": []
        }
    source_metabase.put('/api/dashboard/162/cards', cards_payload)
```

Copied from logs:

`[f75f3988-f28c-4641-97ca-191d283c4f48] 2024-08-23T12:40:18+02:00 DEBUG metabase.server.middleware.log PUT /api/dashboard/162/cards 400 5.4 ms (0 DB calls) 
{:errors {:cards "value must be seq of maps in which ids are unique"},
 :specific-errors {:cards ["invalid type, received: nil"]}}`

**Comment by vvaezian** [comment]
Payload should be passed as the json parameter: `source_metabase.put('/api/dashboard/162/cards', json=cards_payload)`.

**Comment by vvaezian** [comment]
Hi @yasserN,

At Intellimenta we have developed [DataBot](https://intellimenta.com/products/databot/), a conversational analytics app that connects with **Metabase** and enables users to ask questions about data and visualize the results using natural language in their preferred language.
If your company uses Metabase, DataBot can significantly enhance how your team and customers interact with data. 
If you're interested in learning more, you can book a demo using [this](https://outlook.office365.com/owa/calendar/booking@intellimenta.com/bookings/s/ZEMZuuM07U6C4Tr-GKUyOQ2) link. Happy to discuss further.
