### ISSUE TITLE
Deepcopying dashboards may fail with 'None' card ids

### ISSUE THREAD

**Issue by vitoravancini** [vvaezian/metabase_api_python#6]
Hello, found your project in metabase discourse and I'm already using it in my company's deployment pipelines, thankyou!

I had to fix an issue I've found when deepcopying dashboards, for some reason metabase api returned cards with card ids as None. I've added  some None checking at  metabase_api.py around lines 530-560.

I've forked you project with this fix for this case, if youre interested I could open an PR.

**Comment by vvaezian** [comment]
Hi @vitoravancini, I'm glad that my work could help you.

Yes please open a PR.
These `None` values suggest that the values for the 'ordered_cards' key are not being populated correctly in some cases. Metabase team might be interested in looking into this as well.

**Comment by theoaf** [comment]
In my case the `None` card_ids were for text boxes.

P.S. this is my first time using the Metabase API & the python library - and they are very useful

**Comment by vvaezian** [comment]
Hi @theoaf. I'll fix this in the coming days.

**Comment by vvaezian** [comment]
@theoaf Fixed in the new version (0.2.3).  
Run `pip install --upgrade metabase-api` to upgrade to the latest version.

**Comment by theoaf** [comment]
great, will give it a spin this week - have some other dashboards that need copying

**Comment by vvaezian** [comment]
Hi @vitoravancini and @theoaf,
At Intellimenta we have developed [DataBot](https://intellimenta.com/products/databot/), a conversational analytics app that connects with **Metabase** and enables users to ask questions about data and visualize the results using natural language in their preferred language. 
If your company uses Metabase, DataBot can significantly enhance how your team and customers interact with data. If you're interested in learning more, you can book a demo using [this](https://outlook.office365.com/owa/calendar/booking@intellimenta.com/bookings/s/ZEMZuuM07U6C4Tr-GKUyOQ2) link. Happy to discuss further.
