### ISSUE TITLE
Function 'move_to_archive()' returning SyntaxError

### ISSUE THREAD

**Issue by tamires-csilva** [vvaezian/metabase_api_python#8]
Hi!
I am experiencing the following problem:

**The code I am trying to execute is :**
`from metabase_api import Metabase_API`

**Error message**:
`File "/usr/local/lib/python3.6/dist-packages/metabase_api/__init__.py", line 1, in <module>`
         `from metabase_api import Metabase_API`
`File "/usr/local/lib/python3.6/dist-packages/metabase_api/metabase_api.py", line 705`
   ` self.verbose_print(verbose, 'Successfully Archived.') if res == 202 else print('Archiving Failed.')`                                                                                
`^`
`SyntaxError: invalid syntax`

I can't use the other functions because of this error. I commented the function (_move_to_archive()_) and saved using Admin permission  and now it's working. 

Are there any prerequisites for this function (_move_to_archive ()_) works correctly?

**Comment by vvaezian** [comment]
Hi @tamires-csilva 
The issue seems to be that you are using Python2.
The structure `print(x) if y else print(z)` is not recognized in Python2. I'll change the code so that it can be used with Python2 as well.

**Comment by vvaezian** [comment]
Fixed in the new version (0.2.4).
Run `pip install --upgrade metabase-api` to upgrade to the latest version.

**Comment by vvaezian** [comment]
Hi @tamires-csilva, 
At Intellimenta we have developed [DataBot](https://intellimenta.com/products/databot/), a conversational analytics app that connects with your **Metabase** and enables users to ask questions about data and visualize the results using natural language in their preferred language. 
If your company uses Metabase, DataBot can significantly enhance how your team and customers interact with data. If you're interested in learning more, you can book a demo using [this](https://outlook.office365.com/owa/calendar/booking@intellimenta.com/bookings/s/ZEMZuuM07U6C4Tr-GKUyOQ2) link.
